version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app          
      - /app/node_modules        
    environment:
      - NODE_ENV=${NODE_ENV:-development} 
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:${PORT:-5000} 
      - REACT_APP_NEWS_API_KEY=${REACT_APP_NEWS_API_KEY} 
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}" 
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-5000}
      DB_HOST: ${DB_HOST}                
      DB_PORT: ${DB_PORT:-3306}          
      DB_USER: ${DB_USER}                
      DB_PASSWORD: ${DB_PASSWORD}        
      DB_NAME: ${DB_NAME}                
      FINANCIAL_API_KEY: ${FINANCIAL_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000} 
      CHOKIDAR_USEPOLLING: "true"

    volumes:
      - ./backend:/app           
      - /app/node_modules         
    command: npm run dev 

